### ISSUE TITLE
Add config option to disable The Maestro

### ISSUE THREAD

**Issue by OpenBagTwo** [OpenBagTwo/FoxNap#17]
:cry: 

In the spirit of keeping this mod "Vanilla Plus," there should be an option to disable the `conductor` profession for players who prefer to obtain music discs by other means (#16).

This does not need to be part of the initial release but should be done in tandem with #13 (note that without #13, it's pretty trivial to keep Conductors from generating in your world)

### Implementation Suggestion

Should be pretty trivial: just put this line behind an `if` condition:

https://github.com/OpenBagTwo/FoxNap/blob/1.19.2/src/main/java/net/openbagtwo/foxnap/FoxNap.java#L28

**Comment by uczpre** [comment]
Dont need man , the Disco mod exist , it has easier installation too since everything is inside 1 .jar

**Comment by OpenBagTwo** [comment]
I mean, is there any reason _in general_ not just to use the Disco mod?

**Comment by uczpre** [comment]
well , for once it doesnt provide a way for people to acquire the music disc in survival.
the generator is horrible too , it requires us to upload and set a tag manually for each audio file ! upload ? oh yeah , its a website.
while your generator may be missing a few things here and there , its still miles ahead.
in general , the disco mod is not the most featured and convenient mod when compared to your creation ;D
nice mod man !

**Comment by OpenBagTwo** [comment]
This change is live in v0.1.2 for Minecraft 1.19.4-1.20.5. Keeping it open until I backport it to the ole 1.19 build.
