### ISSUE TITLE
Defer Configuration until Loading a World

### ISSUE THREAD

**Issue by OpenBagTwo** [OpenBagTwo/FoxNap#48]
Basically if you mess up your config, you should be able to exit to the main menu, fix it, then go back into the world, instead of having to close Minecraft entirely.

**Comment by uczpre** [comment]
How philisophical for a ubuntu user ? But people wont know unless you document this , as a man with more mods than friends , i always restart after a config change , simple because i dont know for sure how these mods behave :(

**Comment by OpenBagTwo** [comment]
This is tied directly to (if not a prerequisite for) #49

**Comment by OpenBagTwo** [comment]
You get this for free with 1.21 moving all the configuration stuff to datapacks. Closing.
