### ISSUE TITLE
A way to append/subtract files to existing texture packs

### ISSUE THREAD

**Issue by uczpre** [OpenBagTwo/FoxNap#52]
Pretty self explanatory , i would LOVE to be able to add and remove music without screwing with existing music discs and having to learn the black proprietary magic that is minecraft's texture pack syntax/format.
this is less dire than the existing issues with the generator  of course.

**Comment by OpenBagTwo** [comment]
Thanks for the input!

(I still need to figure out what's going on with your other issue)

To clarify: do you mean changing the vanilla records? Or overriding the seven default / included Fox Nap records?

**Comment by uczpre** [comment]
Foxnap's of course :)
if i wanted to overwrite vanilla , ill just use regular texture packs ;D

**Comment by OpenBagTwo** [comment]
I believe this is already the default behavior. I just tried running the executable on my system, and the track numbers started at 1 (meaning it overwrote the built-in tracks). If you're talking about _selectively_ overwriting, you can do that [using the command-line interface](https://github.com/OpenBagTwo/FoxNap?tab=readme-ov-file#advanced-options-command-line-options).

**Comment by uczpre** [comment]
No lol :D

imagine a texture pack has been made , 3 files , A , B and C.
heres how the executable assigns the numbers :
1. A
2. B
3. C

everything is fine , until i want to add a new file called D.
i could manually edit the json and stuff to assign D number 4 , edit the n_disc , and yada yada yada....
which is really time consuming and a boring , if only i could have the exe do that for me.

i guess i could make a new texture pack.... OH NO!!!!
It assigned it like this !
1. A
2. B
3. D
4. C

now all the music disc i have ingame that previously wouldve played C , now plays a remix of never gonna give you up !!!
NOOOOOO !!!!!!!!


as you can see , this is very cringe.
but still , the previous issue is more dire. this feature requestt is as dire as spawning jukeboxes in villages.

**Comment by OpenBagTwo** [comment]
Take a look at the [specs file system](https://github.com/OpenBagTwo/FoxNap?tab=readme-ov-file#advanced-options-spec-file). You can create a spreadsheet in Excel and export as CSV / TSV to tell the resource pack generator which tracks should be assigned which numbers. If you want to leave gaps, you may need to pass in some additional command-line options.

Then, if there are _specific_ textures you want to overwrite, just unzip the resource pack, replace those specific files, and re-zip.

I'm sorry there's not more documentation about the spec file functionality--after I implemented it I kinda realized it was overkill for 99% of users, and the remaining 1% would probably prefer to manually assemble or edit their own texture packs.

Anyway, feel free to try creating a spec file and ping me if you have questions.

**Comment by uczpre** [comment]
Why Thank You ! But my suggestion is to be able to do this directly using the executable , perhaps using some kind of append option ? like how you would with archives files such as .7z  ;D

**Comment by OpenBagTwo** [comment]
Pretty much every archive manager I can think of (FileRoller, Windows Explorer, etc.) supports dragging and dropping files into zip archives. At the _very worst,_ you just have to unzip the archive, drop the files you want in, and then zip everything back up. Sorry, this is a #wontfix
